Blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'

urlpatterns = [
# post views
# path('', views.lista_post, name='lista_post'),
path('', views.lista_post.as_view(), name='lista_post'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.detalle_post, name='detalle_post'),
path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
path('<int:post_id>/comentario/', views.post_comentario, name='post_comentario'),
path('busqueda/', views.busqueda_post, name='busqueda_post'),
]

Contacto/urls.py
from django.urls import path
# load views of these applications.
from . import views

app_name = 'Contacto'

urlpatterns = [
    path('', views.contacto, name='contacto'),
]

PracticaDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogSitemap, StaticSitemap

sitemaps = {
    'static':StaticSitemap, #add StaticSitemap to the dictionary
    'blog':BlogSitemap #add DynamicSitemap to the dictionary
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Proyecto_web_app.urls')),
    path('servicios/', include('Servicios.urls')),
    path('blog/', include('Blog.urls')),
    path('contacto/', include('Contacto.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('cupones/', include('Cupones.urls', namespace='cupones')),
    path('tienda/', include('Tienda.urls')),
    path('carro/', include('Carro.urls')),
    path('cuenta/', include('Autentificacion.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('Orders.urls', namespace='orders')),
    path('__debug__/', include('debug_toolbar.urls')),    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import mimetypes
    mimetypes.add_type('application/javascript', '.js', True)
    mimetypes.add_type('text/css', '.css', True)

Proyecto_web_app/urls.py
from django.urls import path
from . import views

app_name  = 'Proyecto_web_app'

urlpatterns = [
    path('', views.home, name='home'),
    # path('tienda/', views.tienda, name='tienda'),
    # path('contacto/', views.contacto, name='contacto'),
]

Servicios/urls.py
from django.urls import path

from . import views

app_name = 'Servicios'

urlpatterns = [
    path('', views.servicios, name='servicios'),
]

Tienda/urls.py
from django.urls import path
# load views of these applications.
from . import views

app_name = 'Tienda'

urlpatterns = [
    path('', views.tienda, name='tienda'),
]

Proyecto_web_app/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, 'Proyecto_web_app/inicio.html')

Proyecto_web_app/templates/Proyecto_web_app/base.html
{% load django_bootstrap5 %}
{% load static %}
{# para poder carga las etiqueta django_bootstrap5 y static posteriormente #}
{# primero bootstrap y luego nuestro css #}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>

    <!-- Add Bootstrap CSS -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}

    <!-- Nuestro CSS -->
    <link rel="stylesheet" href="{% static 'Proyecto_web_app/css/style.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="/media/Favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/media/Favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/media/Favicon/favicon-16x16.png">
    <link rel="manifest" href="/media/Favicon/site.webmanifest">



</head>

<body>
    <header>
        <h1 class="container-fluid text-center text-white bg-dark py-5">UnikGAME TIENDA VIRTUAL</h1>
        <div style="color: black; text-align: right; margin-right: 100px;">
            {% if user.is_authenticated %}
            Hola, {{user.username}}&nbsp;&nbsp;|&nbsp;&nbsp;
            <!-- <a href="{% url 'logout' %}">Cerrar Sesión</a>&nbsp; -->
            <form id="logout-form" action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Cerrar Sesión</button>
            </form>
            | &nbsp;&nbsp;
            <a href="{% url 'dashboard' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-person"
                    viewBox="0 0 16 16">
                    <path
                        d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664z" />
                </svg>
            </a>
            {% else %}
            <a href="{% url 'login' %}">Login</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a
                href="{% url 'registrar' %}">Registrarse</a>
            {% endif %}
        </div>
        {% include "Proyecto_web_app/nav.html" %}
    </header>

    <div class="fondo">
        <section>
            {% block content%}{% endblock %}
        </section>
    </div>

    <footer class="footer bg-dark text-center text-white">
        <hr>
        <small>
            <a href="#">Política de privacidad</a> ·
            <a href="#">Aviso legal</a> ·
            <a href="#">Cookies</a>
        </small>
        <p class="py-2"><small>(c) UnikGAME 2023</small></p>
    </footer>
    </div>
</body>

</html>

Proyecto_web_app/templates/Proyecto_web_app/inicio.html
<!--Cargamos la plantilla base-->
{% extends "Proyecto_web_app/base.html" %}

<!-- Establecemos el titulo de la página -->
{% block title %}Home{% endblock %}

<!-- Definimos su contenido -->
{% block content %}

    <h2>Esta es la página de Inicio.</h2>

{% endblock %}

Proyecto_web_app/templates/Proyecto_web_app/nav.html
<ul class="nav justify-content-center my-2">

    <li class="nav-item px-lg-4">
        {% url 'Proyecto_web_app:home' as home_url %}
        <a class="nav-link text-uppercase fw-bold text-expanded {% if request.path == home_url %}
        text-black{% endif %}" href="{{ home_url }}">Inicio</a>
    </li>

    <li class="nav-item px-lg-4">
        {% url 'Servicios:servicios' as servicios_url %}
        <a class="nav-link text-uppercase fw-bold text-expanded {% if request.path == servicios_url %}
        text-black{% endif %}" href="{{ servicios_url }}">Servicios</a>
    </li>

    <li class="nav-item px-lg-4">
        {% url 'Blog:lista_post' as blog_url %}
        <a class="nav-link text-uppercase fw-bold text-expanded {% if request.path|slice:':6' == blog_url %}
        text-black{% endif %}" href="{{ blog_url }}">Blog</a>
    </li>

    <li class="nav-item px-lg-4">
        {% url 'Tienda:tienda' as tienda_url %}
        <a class="nav-link text-uppercase fw-bold text-expanded {% if request.path == tienda_url %}
        text-black{% endif %}" href="{{ tienda_url }}">Tienda</a>
    </li>

    <li class="nav-item px-lg-4">
        {% url 'Contacto:contacto' as contacto_url %}
        <a class="nav-link text-uppercase fw-bold text-expanded {% if request.path == contacto_url %}
        text-black{% endif %}" href="{{ contacto_url }}">Contacto</a>
    </li>
</ul>

Proyecto_web_app/templates/Proyecto_web_app/paginacion.html
<div>
    <ul class="pagination">
        {% if page.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.previous_page_number }}">
                    Anterior
                </a>
            </li>
        {% endif %}

        <li class="page-item">
            <a class="page-link" href="#">
                Página {{ page.number }} de {{ page.paginator.num_pages }}
            </a>
        </li>

        {% if page.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.next_page_number }}">
                    Siguiente
                </a>
            </li>
        {% endif %}
    </ul>
</div>