Blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'

urlpatterns = [
# post views
# path('', views.lista_post, name='lista_post'),
path('', views.lista_post.as_view(), name='lista_post'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.detalle_post, name='detalle_post'),
path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
path('<int:post_id>/comentario/', views.post_comentario, name='post_comentario'),
path('busqueda/', views.busqueda_post, name='busqueda_post'),
]

Carro/urls.py
from django.urls import path
# load views of these applications.
from . import views

app_name = 'carro'

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
    path('mostrar/', views.mostrar_carro, name='mostrar'),
    ]

Cupones/urls.py
from django.urls import path
from . import views

app_name = 'cupones'

urlpatterns = [
    path('aplicar/', views.aplicar_cupon, name='aplicar'),
]

Orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/Order/<int:order_id>/', views.admin_order_detail,
         name='admin_order_detail'),
    path('admin/Order/<int:order_id>/pdf/',
         views.admin_order_pdf, name='admin_order_pdf'),
]

PracticaDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogSitemap, StaticSitemap

sitemaps = {
    'static':StaticSitemap, #add StaticSitemap to the dictionary
    'blog':BlogSitemap #add DynamicSitemap to the dictionary
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Proyecto_web_app.urls')),
    path('servicios/', include('Servicios.urls')),
    path('blog/', include('Blog.urls')),
    path('contacto/', include('Contacto.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('cupones/', include('Cupones.urls', namespace='cupones')),
    path('tienda/', include('Tienda.urls')),
    path('carro/', include('Carro.urls')),
    path('cuenta/', include('Autentificacion.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('Orders.urls', namespace='orders')),
    path('__debug__/', include('debug_toolbar.urls')),    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import mimetypes
    mimetypes.add_type('application/javascript', '.js', True)
    mimetypes.add_type('text/css', '.css', True)

Tienda/urls.py
from django.urls import path
# load views of these applications.
from . import views

app_name = 'Tienda'

urlpatterns = [
    path('', views.tienda, name='tienda'),
]

Tienda/models.py
from django.db import models

# Create your models here.

# Creamos dos modelos para la categoría del producto (tipo de consola)
# y para el producto (el juego en si).


class CategoriaProducto(models.Model):
    """Registrará las diferentes consolas para las que vendemos juegos"""

    nombre = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["nombre"]
        indexes = [
            models.Index(fields=["nombre"]),
        ]
        verbose_name = "categoriaProducto"
        verbose_name_plural = "categoriasProductos"

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    """Registra los propios juegos en si."""

    nombre = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    categoria = models.ForeignKey(
        CategoriaProducto, on_delete=models.CASCADE, related_name="categoria_productos"
    )
    descripcion = models.CharField(blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.BooleanField(default=True)
    # hay que tener instalado la libreria pillow para poder subir imagenes
    imagen = models.ImageField(upload_to="Tienda", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["nombre"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["nombre"]),
            models.Index(fields=["-created"]),
        ]
        verbose_name = "producto"
        verbose_name_plural = "productos"

    def __str__(self):
        return self.nombre

Tienda/views.py
from django.shortcuts import render

# Como trabajamos con productos vamos a importarlos
from Tienda.models import Producto

# Create your views here.

def tienda(request):
    productos = Producto.objects.filter(stock=True)
    # carga en la variable productos todos los juegos que hayamos introducido a través
    # del panel de administración de Django.
    contexto = {
        "productos": productos,
    }
    
    return render(request, "Tienda/tienda.html", contexto)   

Tienda/templates/Tienda/carro_detalle.html
<!--Cargamos la plantilla base-->
{% extends "Proyecto_web_app/base.html" %}
{% load thumbnail %}

<!-- Establecemos el titulo de la página -->
{% block title %}Carro{% endblock %}

<!-- Definimos su contenido -->
{% block content %}
<div class="container">
    <div class="bg-white text-black">
        {% with total_items=carro|length %}
        {% if total_items > 0 %}
        <h1>Tu Carro de la Compra</h1>
        <p class="ms-3">
            <a href="{% url 'carro:limpiar' %}" style="color: #0fa4b8; text-decoration: none;" class="link">
                Anular la selección de todos los artículos</a>
        </p>
        <hr>
    </div>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Eliminar</th>
                <th>Precio Unitario</th>
                <th>total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in carro %}
            {% with producto=item.producto %}
            <tr>
                <td>
                    <img src="{% thumbnail producto.imagen 100x0 %}">
                </td>
                <td>{{ producto.nombre }}</td>
                <td>{{ item.cantidad }}</td>
                <td>
                    <a href="{% url 'carro:eliminar' producto.id %}" class="btn btn-danger">Eliminar</a>
                    <a href="{% url 'carro:restar' producto.id %}" class="btn btn-primary">Restar 1 ud</a>

                </td>
                <td class="num">{{ item.precio }} €</td>
                <td class="num">{{item.precio_total}} €</td>
            </tr>
            {% endwith %}
            {% endfor %}
            <!-- <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">{{ carro.get_total_price }} €</td>
            </tr> -->
            {% if carro.cupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td class="num">{{ carro.get_total_price|floatformat:2 }} €</td>
            </tr>
            <tr>
                <td>
                    "{{ carro.cupon.codigo }}" cupón
                    ({{ carro.cupon.descuento}}% descuento)
                </td>
                <td colspan="4"></td>
                <td class="num neg">
                    - {{ carro.conseguir_descuento|floatformat:2 }} €
                </td>
            </tr>
            {% endif %}
            <tr class="Total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">
                    {{ carro.precio_total_despues_de_descuento|floatformat:2 }} €
                </td>
            </tr>
        </tbody>
    </table>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>¿Tienes un cupón?:</p>
                <form action="{% url 'cupones:aplicar' %}" method="post">
                    {{ formulario_cupon }}
                    <input type="submit" value="Aplicar" class="btn btn-primary">
                    {% csrf_token %}
                </form>
            </div>
            <div class="col-md-6">
                <div class="d-flex justify-content-end">
                    <p class="text-right">
                        <a href="{% url 'Tienda:tienda' %}" class="btn btn-primary">Continua comprando</a>
                        <a href="{% url 'orders:order_create' %}" class="btn btn-success ml-2">Checkout</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div>
        {% if productos_recomendados %}
        <h3 style="color:aliceblue;">Comprados juntos habitualmente</h3>
        <div class="row">
            {% for p in productos_recomendados %}
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'carro:agregar' p.id %}">
                            <img src="{% thumbnail p.imagen 100x0 %}" class="img-fluid">
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'carro:agregar' p.id %}" style="color: black;">
                            {{ p.nombre }}
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>



    {% else %}
    <div class="container py-4">
        <div class="bg-white text-black">
            <h3 class="ms-3 pt-3">Tu cesta de UnikGAME está vacía.</h3>
            <p class="ms-3 pb-3">Revisa tus productos guardados para más tarde o
                <a href="{% url 'Tienda:tienda' %}">continúa comprando.</a>
            </p>
        </div>
    </div>
    {% endif %}
    {% endwith %}

</div>
{% endblock %}

Tienda/templates/Tienda/tienda.html
<!--Cargamos la plantilla base-->
{% extends "Proyecto_web_app/base.html" %}
{% load thumbnail %}

<!-- Establecemos el titulo de la página -->
{% block title %}Tienda{% endblock %}

<!-- Definimos su contenido -->
{% block content %}
<h1 class="text-center">Elige tu Consola.</h1>

<div class="container">
  <div class="bg-dark">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" id="ps4-tab" data-bs-toggle="tab" href="#ps4" role="tab" aria-controls="ps4"
          aria-selected="true">PS4</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="ps5-tab" data-bs-toggle="tab" href="#ps5" role="tab" aria-controls="ps5"
          aria-selected="false">PS5</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="xbox-tab" data-bs-toggle="tab" href="#xbox" role="tab" aria-controls="xbox"
          aria-selected="false">Xbox</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="xbox-tab" data-bs-toggle="tab" href="#nintendo" role="tab" aria-controls="xbox"
          aria-selected="false">Nintendo</a>
      </li>
    </ul>
  </div>


  <div class="tab-content">

    <!--colocamos el carrito en un float en la parte derecha -->
    <div style="float:right">
      <div>CESTA</div>
      {% include "carro/widget.html" %}
    </div>

    <div class="tab-pane fade show active" id="ps4" role="tabpanel" aria-labelledby="ps4-tab">
      <h3>Juegos PS4</h3>
      <div class="row g-4">
        {% for producto in productos %}
        {% if producto.categoria_id == 1 %}
        <div class="col-md-3">
          <div class="card h-100" style="width:200px">
            <!-- <img class="card-img-top" src="{{producto.imagen.url}}" alt="Card image"> -->
            <img class="card-img-top" src="{% thumbnail producto.imagen 200x0 %}" alt="Card image">
            <div class="card-body">
              <h4 class="card-title">{{producto.nombre}}</h4>
              <p class="card-text">{{producto.precio}} €</p>
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al Carro</a>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="tab-pane fade show" id="ps5" role="tabpanel" aria-labelledby="ps5-tab">
      <h3>Juegos PS5</h3>
      <div class="row g-4">
        {% for producto in productos %}
        {% if producto.categoria_id == 2 %}
        <div class="col-md-3">
          <div class="card h-100" style="width:200px">
            <!-- <img class="card-img-top" src="{{producto.imagen.url}}" alt="Card image"> -->
            <img class="card-img-top" src="{% thumbnail producto.imagen 200x0 %}" alt="Card image">
            <div class="card-body">
              <h4 class="card-title">{{producto.nombre}}</h4>
              <p class="card-text">{{producto.precio}} €</p>
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al Carro</a>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>

    

    <div class="tab-pane fade" id="xbox" role="tabpanel" aria-labelledby="xbox-tab">
      <h3>Juegos Xbox</h3>
      <!-- Contenido para juegos Xbox -->
      <div class="row g-4">
        {% for producto in productos %}
        {% if producto.categoria_id == 3 %}
        <div class="col-md-3">
          <div class="card h-100" style="width:200px">
            <!-- <img class="card-img-top" src="{{producto.imagen.url}}" alt="Card image"> -->
            <img class="card-img-top" src="{% thumbnail producto.imagen 200x0 %}" alt="Card image">
            <div class="card-body">
              <h4 class="card-title">{{producto.nombre}}</h4>
              <p class="card-text">{{producto.precio}} €</p>
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al Carro</a>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="tab-pane fade" id="nintendo" role="tabpanel" aria-labelledby="xbox-tab">
      <h3>Juegos Nintendo</h3>
      <!-- Contenido para juegos Nintendo -->
      <div class="row g-4">
        {% for producto in productos %}
        {% if producto.categoria_id == 4 %}
        <div class="col-md-3">
          <div class="card h-100" style="width:200px">
            <img class="card-img-top" src="{% thumbnail producto.imagen 200x0 %}" alt="Card image">
            <div class="card-body">
              <h4 class="card-title">{{producto.nombre}}</h4>
              <p class="card-text">{{producto.precio}} €</p>
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al Carro</a>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}