Blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'

urlpatterns = [
# post views
# path('', views.lista_post, name='lista_post'),
path('', views.lista_post.as_view(), name='lista_post'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.detalle_post, name='detalle_post'),
path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
path('<int:post_id>/comentario/', views.post_comentario, name='post_comentario'),
path('busqueda/', views.busqueda_post, name='busqueda_post'),
]

PracticaDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogSitemap, StaticSitemap

sitemaps = {
    'static':StaticSitemap, #add StaticSitemap to the dictionary
    'blog':BlogSitemap #add DynamicSitemap to the dictionary
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Proyecto_web_app.urls')),
    path('servicios/', include('Servicios.urls')),
    path('blog/', include('Blog.urls')),
    path('contacto/', include('Contacto.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('cupones/', include('Cupones.urls', namespace='cupones')),
    path('tienda/', include('Tienda.urls')),
    path('carro/', include('Carro.urls')),
    path('cuenta/', include('Autentificacion.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('Orders.urls', namespace='orders')),
    path('__debug__/', include('debug_toolbar.urls')),    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import mimetypes
    mimetypes.add_type('application/javascript', '.js', True)
    mimetypes.add_type('text/css', '.css', True)

Blog/models.py
from django.db import models

from django.contrib.auth.models import User

# Para importar el usuario que esta creando el post

from django.utils import timezone

# Para importar el timezone y establecer la fecha de creación.

from django.urls import reverse

# Para crear la Url canónica


# Create your models here.
class Categoria(models.Model):
    """Diferentes tags para asignar a los post"""

    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre


class Post(models.Model):
    titulo = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique_for_date='created')
    contenido = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    categorias = models.ManyToManyField(Categoria, blank=True, related_name="categoria_post")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Model meta Options - https://docs.djangoproject.com/en/4.1/topics/db/models/#meta-options
    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"
        ordering = ['-updated']
        indexes = [
            models.Index(fields=['updated']),
        ]

    def __str__(self):
        return self.titulo
    
    def get_absolute_url(self):
        return reverse("Blog:detalle_post", 
                       args=[self.created.year,
                             self.created.month,
                             self.created.day,
                             self.slug])

class Comentario(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comentarios')
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_comentarios')
    email = models.EmailField()
    cuerpo = models.TextField(max_length=400)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    activo = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]
    
    def __str__(self):
        return f"Comentario de {self.autor} en {self.post}"

Blog/forms.py
from django import forms
from .models import Comentario

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['autor', 'email', 'cuerpo']
        
class BusquedaForm(forms.Form):
    consulta = forms.CharField()
    

Blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404

from .models import Post, Categoria, Comentario

# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import ListView

# Importamos el formulario para los comentarios de cada post.
from .forms import ComentarioForm, BusquedaForm
from django.views.decorators.http import require_POST

# Para realizar busquedas en los campos de los post.
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


# Create your views here.


class lista_post(ListView):
    """
    Una alternativa a la función lista_post
    """

    model = Post
    context_object_name = "posts"
    paginate_by = 3
    template_name = "Blog/lista.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categorias"] = Categoria.objects.all()
        return context


# def lista_post(request):
#     posts = get_list_or_404(Post)
#     categorias = get_list_or_404(Categoria)
#     # Paginación con 3 post por página.
#     paginador = Paginator(posts, 3)
#     numero_pagina = request.GET.get('page', 1)
#     try:
#         posts_por_pagina = paginador.page(numero_pagina)
#     except EmptyPage:
#         # Si la página está fuera del rango de las paginas de resultados
#         posts_por_pagina = paginador.page(paginador.num_pages)
#     except PageNotAnInteger:
#         # Si el párametro introducido no es un número entero
#         posts_por_pagina = paginador.page(1)
#     return render(
#         request, "Blog/lista.html", {"posts": posts_por_pagina, "categorias": categorias}
#     )


def detalle_post(request, year, month, day, post):
    """Muestra todos los post"""
    post = get_object_or_404(
        Post,
        slug=post,
        created__year=year,
        created__month=month,
        created__day=day,
    )
    # Lista de comentarios activos para este post.
    comentarios = post.comentarios.filter(activo=True)
    # Formulario para que los usuarios comenten los post.
    form = ComentarioForm()
    return render(
        request,
        "Blog/detalle.html",
        {"post": post, "comentarios": comentarios, "form": form},
    )


def categoria(request, categoria_id):
    """Muesta una lista de post en base a su categoría"""
    categoria = Categoria.objects.get(id=categoria_id)
    posts = Post.objects.filter(categorias=categoria_id)
    return render(
        request, "Blog/categoria.html", {"categoria": categoria, "posts": posts}
    )


@require_POST
def post_comentario(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comentario = None
    # Se ha publicado un comentario
    form = ComentarioForm(data=request.POST)
    if form.is_valid:
        # creamos un objeto 'comentario' pero sin guardarlo en la base de datos.
        comentario = form.save(commit=False)
        # asignamos el post al comentario
        comentario.post = post
        comentario.save()
    return render(
        request,
        "Blog/comentario.html",
        {"post": post, "form": form, "comentario": comentario},
    )


def busqueda_post(request):
    formulario = BusquedaForm()
    consulta = None
    resultados = []

    if "consulta" in request.GET:
        formulario = BusquedaForm(request.GET)
        if formulario.is_valid():
            consulta = formulario.cleaned_data["consulta"]
            vector_busqueda = SearchVector(
                "titulo", weight="A", config="spanish"
            ) + SearchVector("contenido", weight="B", config="spanish")
            consulta_busqueda = SearchQuery(consulta, config="spanish")
            resultados = (
                Post.objects.annotate(
                    search=vector_busqueda,
                    rank=SearchRank(vector_busqueda, consulta_busqueda),
                )
                .filter(rank__gte=0.3)
                .order_by("-rank")
            )

    return render(
        request,
        "Blog/busqueda.html",
        {"formulario": formulario, "consulta": consulta, "resultados": resultados},
    )

Blog/templates/Blog/busqueda.html
<!--Cargamos la plantilla base-->
{% extends "Proyecto_web_app/base.html" %}

<!-- Cargamos la etiqueta personalizada -->
{% load blog_tags %}

<!-- Establecemos el titulo de la página -->
{% block title %}Busqueda{% endblock %}

{% block content %}

<div class="container-fluid bg-white" style="margin-bottom: 50px;">

{% if consulta %}
    <h1>Post que contienen la consulta "{{ consulta|truncatewords:15 }}"</h1>
    <h3>
    {% with resultados.count as total_results %}
        Encontrados {{ total_results }} resultado{{total_results|pluralize}}
    {% endwith %}
    </h3>
    {% for post in resultados %}
    <h4>
        <a href="{{ post.get_absolute_url }}">
            {{ post.titulo }}
        </a>
    </h4>
    {{ post.contenido|markdown|truncatewords_html:12 }}
    {% empty %}
    <p>No hay resultados para la consulta.</p>
    {% endfor %}

    <p><a href="{% url 'Blog:busqueda_post' %}">Realizar nueva búsqueda</a></p>

{% else %}
    <h1>Busqueda en los Posts</h1>
    <form method="get">
        {{ formulario.as_p }}
        <input type="submit" value="Busqueda">
    </form>
{% endif %}

</div>

{% endblock %}

Blog/templates/Blog/categoria.html
<!--Cargamos la plantilla base-->
{% extends "Proyecto_web_app/base.html" %}

<!-- Establecemos el titulo de la página -->
{% block title %}Post por Categorias{% endblock %}

{% block content %}
<div class="container-fluid bg-white" style="margin-bottom: 50px;">
    <h1 class="text-center">Listado de Post publicados por "{{categoria}}"</h1>
    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">{{post.titulo}}</a>
    </h2>
    <p class="date">Publicado {{ post.autor }} por {{ post.updated }} </p>
    {{ post.contenido|truncatewords:30|linebreaks }}
    {% endfor %}
</div>
<!-- Contenedor para centrar el botón de regresar a la lista de posts -->
<div class="d-flex justify-content-center align-items-center">
    <a href="{% url 'Blog:lista_post' %}" class="btn btn-primary">Regresar</a>
</div>
{% endblock %}

Blog/templates/Blog/comentario.html
{% extends "Proyecto_web_app/base.html" %}

{% block title %}Añade un comentario{% endblock %}

{% block content %}
    {% if comentario %}
    <div style="background-color: beige;">
        <h2>Tu comentario ha sido añadido</h2>
        <p><a href="{{post.get_absolute_url}}">Vuelve al Post</a></p>
    </div>
    {% else %}
        {% include "Blog/form_comentario.html" %}
    {% endif %}
{% endblock%}

Blog/templates/Blog/detalle.html
{% extends "Proyecto_web_app/base.html" %}

{% load blog_tags %}

{% block title %}Detalle de un Post{% endblock %}

{% block content %}
<div class="container-fluid bg-white" style="margin-bottom: 150px;">
    <h1>{{ post.titulo }}</h1>

    <p class="date">Publicado {{ post.autor }} por {{ post.updated }} </p>

    {{ post.contenido|markdown }}    

    {% with comentarios.count as total_comentarios %}
    <h2>
        {{ total_comentarios }} comentario{{ total_comentarios|pluralize }}
    </h2>
    {% endwith %}

    {% for comentario in comentarios %}
    <div class="comment">
        <p class="info">
            Comentario {{ forloop.counter }} de {{ comentario.autor }} -
            {{ comentario.created }}
        </p>
        {{ comentario.cuerpo|linebreaks }}
    </div>

    {% empty %}
    <p>No hay comentarios aún.</p>

    {% endfor %}

    <!-- Contenedor para centrar el botón de regresar a la lista de posts -->
    <div class="d-flex justify-content-center align-items-center">
        <a href="{% url 'Blog:lista_post' %}" class="btn btn-primary">Regresar</a>
    </div>
    {% include "Blog/form_comentario.html" %}
</div>
{% endblock %}

Blog/templates/Blog/form_comentario.html
<h2 style="margin-bottom: 4px;">Añade un nuevo comentario</h2>
<form action="{% url 'Blog:post_comentario' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Añade comentario"></p>
</form>

Blog/templates/Blog/lista.html
<!--Cargamos la plantilla base-->
{% extends "Proyecto_web_app/base.html" %}

<!-- Cargamos la etiqueta personalizada -->
{% load blog_tags %}

<!-- Establecemos el titulo de la página -->
{% block title %}Blog{% endblock %}

{% block content %}

<div class="container-fluid bg-white" style="margin-bottom: 50px;">

    <h1 class="text-center">Listado de Post publicados</h1>
    <div id="sidebar">
        <h2>El Blog</h2>
        <p>
            Hay escritos {% posts_totales %} posts hasta el momento.
        </p>
        <h3>Últimos Posts</h3>
        {% mostrar_ultimos_posts 3 %}
        <h3>Post más comentados</h3>
        {% obtener_posts_mas_comentados as posts_mas_comentados %}
        <ul>
            {% for post in posts_mas_comentados %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.titulo }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">{{post.titulo}}</a>
    </h2>
    <p class="date">Publicado {{ post.autor }} por {{ post.updated }} </p>
    <!-- {{ post.contenido|truncatewords:30|linebreaks }} -->
    {{ post.contenido|markdown|truncatewords_html:15}}
    {% endfor %}
</div>

<!-- {% include "Proyecto_web_app/paginacion.html" with page=posts %} -->
{% include "Proyecto_web_app/paginacion.html" with page=page_obj %}

<section>
    <div style="width: 75%; margin: auto; color: white; text-align: center;">
        Categorías:
        {% for categoria in categorias %}
        <a href="{% url 'Blog:categoria' categoria.id %}" class="link-info">
            <span style="color:rgb(2, 7, 59)">{{ categoria.nombre }}</span>
        </a>&nbsp;&nbsp;&nbsp;
        {% endfor %}
    </div>
</section>

{% endblock %}

Blog/templates/Blog/ultimos_posts.html
<ul>
    {% for post in ultimos_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.titulo }}</a>
    </li>
    {% endfor %}
</ul>