Blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'

urlpatterns = [
# post views
# path('', views.lista_post, name='lista_post'),
path('', views.lista_post.as_view(), name='lista_post'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.detalle_post, name='detalle_post'),
path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
path('<int:post_id>/comentario/', views.post_comentario, name='post_comentario'),
path('busqueda/', views.busqueda_post, name='busqueda_post'),
]

Payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

PracticaDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogSitemap, StaticSitemap

sitemaps = {
    'static':StaticSitemap, #add StaticSitemap to the dictionary
    'blog':BlogSitemap #add DynamicSitemap to the dictionary
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Proyecto_web_app.urls')),
    path('servicios/', include('Servicios.urls')),
    path('blog/', include('Blog.urls')),
    path('contacto/', include('Contacto.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('payment/', include('Payment.urls', namespace='payment')),
    path('cupones/', include('Cupones.urls', namespace='cupones')),
    path('tienda/', include('Tienda.urls')),
    path('carro/', include('Carro.urls')),
    path('cuenta/', include('Autentificacion.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('Orders.urls', namespace='orders')),
    path('__debug__/', include('debug_toolbar.urls')),    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import mimetypes
    mimetypes.add_type('application/javascript', '.js', True)
    mimetypes.add_type('text/css', '.css', True)

Payment/models.py
from django.db import models

# Create your models here.

Payment/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from decimal import Decimal
import stripe
from django.conf import settings
from Orders.models import Order


# Creamos la instancia de Stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))

        # Stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'eur',
                    'product_data': {
                        'name': item.product.nombre,
                    },
                },
                'quantity': item.quantity,
            })
        # Stripe coupon
        if order.cupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.cupon.codigo, percent_off=order.descuento, duration='once')
            session_data['discounts'] = [{'coupon': stripe_coupon.id}]

        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        # redirect to Stripe payment form
        return redirect(session.url, code=303)
    else:
        return render(request, 'Payment/process.html', locals())


def payment_completed(request):
    return render(request, 'Payment/completed.html')


def payment_canceled(request):
    return render(request, 'Payment/canceled.html')

Payment/templates/Payment/canceled.html
{% extends "Proyecto_web_app/base.html" %}

{% block title %}Payment canceled{% endblock %}

{% block content %}
<h1>Pago NO REALIZADO</h1>
<p>Ha habido un problema al procesar el pago.</p>
{% endblock %}

Payment/templates/Payment/completed.html
{% extends "Proyecto_web_app/base.html" %}

{% block title %}Payment successful{% endblock %}

{% block content %}
<h1>Pago Realizado.</h1>
<p>Su pago ha sido realizado correctamente.</p>
<p>¡Muchas Gracias!</p>
{% endblock %}

Payment/templates/Payment/process.html
<!--Cargamos la plantilla base-->
{% extends "Proyecto_web_app/base.html" %}
{% load thumbnail %}
{% load static %}

<!-- Establecemos el titulo de la página -->
{% block title %}Pagar el Pedido{% endblock %}

<!-- Definimos su contenido -->
{% block content %}
<div class="container">
    <h1>Resumen del Pedido</h1>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Producto</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
            <tr>
                <td>
                    <!-- <img src="{% thumbnail item.product.imagen 100x0 %}"> -->
                    {% if item.product.imagen %}
                    <!-- Si hay una imagen, mostrarla con la etiqueta thumbnail -->
                    <img src="{% thumbnail item.product.imagen 100x0 %}">
                    {% else %}
                    <!-- Si no hay una imagen, mostrar una imagen predeterminada -->
                    <img src="{% static '/Proyecto_web_app/img/no_image.png' %}">
                    {% endif %}

                </td>
                <td>{{ item.product.nombre }}</td>
                <td class="num">{{ item.price }}€</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">{{ item.get_cost }}€</td>
            </tr>
            {% endfor %}

            {% if order.cupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="3"></td>
                <td class="num">
                    {{ order.coste_total_antes_del_descuento|floatformat:2 }} €
                </td>
            </tr>
            <tr>
                <td>
                    "{{ order.cupon.codigo }}" cupón
                    ({{ order.descuento }}% descuento)
                </td>
                <td colspan="3"></td>
                <td class="num neg">
                    - {{ order.aplicar_descuento|floatformat:2 }} €
                </td>
            </tr>
            {% endif %}
            <tr>
                <td>Total</td>
                <td colspan="3"></td>
                <td class="num">{{ order.get_total_cost|floatformat:2 }} €</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex justify-content-end">
        <p class="text-right">
        <form action="{% url 'payment:process' %}" method="post">
            <input type="submit" value="Pagar">
            {% csrf_token %}
        </form>
        </p>
    </div>

</div>
{% endblock %}